---

- name: Install programming languages and tools.
  pkgng:
    name: >
      go,
      openjdk8,
      maven,
      postgresql96-server,
      postgresql96-contrib

- name: Enable PostgreSQL.
  lineinfile:
    path: /etc/rc.conf
    regexp: '^postgresql_enable='
    line: 'postgresql_enable="YES"'

- name: Init PostgreSQL database.
  command: /usr/local/etc/rc.d/postgresql initdb
  args:
    creates: /var/db/postgres/data96

